version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web1
      - web2
    ports:
      - 8888:80 
  web1:
    build: 
      context: .
      dockerfile: build/build-image.dockerfile
      args:
        project_name: $project_name
    ports:
      - '8001:80'
  web2:
    build:
      context: .
      dockerfile: build/build-image.dockerfile
      args:
        project_name: $project_name
    ports:
      - '8002:80'